name: macad-mep-graph
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.12
  - panel>=1.3.0
  - networkx>=3.0
  - bokeh>=3.3.0
  - matplotlib>=3.7.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - lxml>=4.9.0
  - plotly>=5.15.0
  - param>=2.0.0
  - holoviews>=1.17.0
  - pip
  - pip:
    - panel[recommended]
